# Generated by Django 5.1 on 2024-11-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblafiliacion',
            name='id_eapb',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbldisbasuras',
            name='id_dis_basuras',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblnivelacademico',
            name='id_nivel_acad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblregimen',
            name='id_regimen',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbltiposcultivo',
            name='id_tip_cultivo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbltiposdevivienda',
            name='id_tip_vivienda',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbltiposservipubli',
            name='id_tip_ser_publi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
