# Generated by Django 5.1 on 2024-08-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltipidentidad',
            name='des_tip_identidad',
            field=models.CharField(max_length=50),
        ),
    ]
