# Generated by Django 5.1 on 2024-11-13 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tblafiliacion_id_eapb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbldatper',
            old_name='tip_iden_usu',
            new_name='des_tip_identidad',
        ),
    ]
