# Generated by Django 5.1 on 2024-11-17 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_tip_iden_usu_tbldatper_des_tip_identidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbldatper',
            name='des_tip_identidad',
        ),
        migrations.RemoveField(
            model_name='tbldatper',
            name='nombre_eapb',
        ),
        migrations.AddField(
            model_name='tbldatper',
            name='id_eapb',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tbldatper',
            name='tip_iden_usu',
            field=models.ForeignKey(blank=True, db_column='id_tip_identidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tbltipidentidad'),
        ),
        migrations.AlterField(
            model_name='tbltipidentidad',
            name='id_tip_identidad',
            field=models.CharField(default='DNI', max_length=12, primary_key=True, serialize=False, verbose_name='Tipo de Identidad'),
        ),
    ]
