# Generated by Django 5.1 on 2024-11-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_tbldatper_des_tip_identidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbltiposdevivienda',
            options={'verbose_name': 'Tipo de Vivienda', 'verbose_name_plural': 'Tipos de Vivienda'},
        ),
        migrations.RemoveField(
            model_name='tbltiposdevivienda',
            name='arrendada',
        ),
        migrations.RemoveField(
            model_name='tbltiposdevivienda',
            name='familiar',
        ),
        migrations.RemoveField(
            model_name='tbltiposdevivienda',
            name='moderna',
        ),
        migrations.RemoveField(
            model_name='tbltiposdevivienda',
            name='propia',
        ),
        migrations.RemoveField(
            model_name='tbltiposdevivienda',
            name='tradicion',
        ),
        migrations.AddField(
            model_name='tbltiposdevivienda',
            name='tipo_vivienda',
            field=models.CharField(choices=[('tradicional', 'Tradicional'), ('moderna', 'Moderna'), ('propia', 'Propia'), ('arrendada', 'Arrendada'), ('familiar', 'Familiar')], default='tradicional', max_length=20, verbose_name='Tipo de Vivienda'),
        ),
    ]
