# Generated by Django 5.1 on 2024-11-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tbltiposdevivienda_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblnivelacademico',
            name='basica_promaria',
        ),
        migrations.RemoveField(
            model_name='tblnivelacademico',
            name='basica_secundaria',
        ),
        migrations.RemoveField(
            model_name='tblnivelacademico',
            name='doctorado',
        ),
        migrations.RemoveField(
            model_name='tblnivelacademico',
            name='especialista',
        ),
        migrations.RemoveField(
            model_name='tblnivelacademico',
            name='media_vocacional',
        ),
        migrations.RemoveField(
            model_name='tblnivelacademico',
            name='phd',
        ),
        migrations.RemoveField(
            model_name='tblnivelacademico',
            name='preescolar',
        ),
        migrations.RemoveField(
            model_name='tblnivelacademico',
            name='primaria_incompleta',
        ),
        migrations.RemoveField(
            model_name='tblnivelacademico',
            name='profesional_universita',
        ),
        migrations.RemoveField(
            model_name='tblnivelacademico',
            name='tecnico',
        ),
        migrations.RemoveField(
            model_name='tblnivelacademico',
            name='tecnologo',
        ),
    ]
