# Generated by Django 5.1 on 2024-11-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_tblnivelacademico_basica_promaria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblnivelacademico',
            options={'verbose_name': 'des_nivel_academico', 'verbose_name_plural': 'des_nivel_academico'},
        ),
        migrations.AlterField(
            model_name='tblnivelacademico',
            name='des_nivel_academico',
            field=models.CharField(choices=[('des_nivel_academico', 'des_nivel_academico')], default='ninguno', max_length=30, verbose_name='des_nivel_academico'),
        ),
    ]
