# Generated by Django 5.1 on 2024-11-17 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_tbleps_alter_tbldatper_nivel_de_academico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='id_eapb',
            field=models.ForeignKey(blank=True, db_column='id_Eps', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tbleps'),
        ),
    ]
