# Generated by Django 5.1 on 2024-11-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_tbldatper_id_eapb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbleps',
            options={'verbose_name': 'des_Eps', 'verbose_name_plural': 'des_Eps'},
        ),
        migrations.AlterField(
            model_name='tbleps',
            name='des_Eps',
            field=models.CharField(choices=[('eps', 'eps')], default='ninguno', max_length=20, verbose_name='des_Eps'),
        ),
    ]
