# Generated by Django 5.1 on 2024-11-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_tbleps_options_alter_tbleps_des_eps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbleps',
            options={},
        ),
        migrations.AlterField(
            model_name='tbldatper',
            name='id_eapb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbleps',
            name='des_Eps',
            field=models.CharField(max_length=20),
        ),
    ]
