# Generated by Django 5.1 on 2024-11-18 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_tbleps_options_alter_tbldatper_id_eapb_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblEps',
        ),
        migrations.AlterField(
            model_name='tbldatper',
            name='id_eapb',
            field=models.ForeignKey(blank=True, db_column='codigo_eapb', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tblafiliacion'),
        ),
    ]
