# Generated by Django 5.1 on 2025-01-06 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_tbldatper_regimen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='regimen',
            field=models.ForeignKey(blank=True, db_column='des_regimen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tblregimen'),
        ),
    ]
