# Generated by Django 5.1 on 2025-01-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_tbldatper_regimen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbldatper',
            old_name='id_eapb',
            new_name='codigo_eapb',
        ),
    ]
