# Generated by Django 5.1 on 2025-01-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_rename_id_eapb_tbldatper_codigo_eapb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblnivelacademico',
            name='des_nivel_academico',
            field=models.CharField(choices=[('des_nivel_academico', 'des_nivel_academico'), ('primaria', 'primaria'), ('secundaria', 'secundaria'), ('ninguno', 'ninguno'), ('licenciatura', 'licenciatura'), ('maestria', 'maestria'), ('doctorado', 'doctorado')], default='ninguno', max_length=30, verbose_name='des_nivel_academico'),
        ),
    ]
