# Generated by Django 5.1 on 2025-01-26 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_tblnivelacademico_des_nivel_academico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='id_tip_vivienda',
            field=models.ForeignKey(blank=True, db_column='tipo_vivienda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tbltiposdevivienda'),
        ),
        migrations.AlterField(
            model_name='tbldatper',
            name='tip_iden_usu',
            field=models.ForeignKey(blank=True, db_column='des_tip_identidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tbltipidentidad'),
        ),
    ]
