# Generated by Django 5.1 on 2025-01-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_tbldatper_id_tip_vivienda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldatper',
            name='numero_familia',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
