# Generated by Django 4.2.6 on 2025-02-06 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_tbldatper_id_tip_vivienda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblafiliacion',
            old_name='nombre_eapb',
            new_name='nombre_eapbAfiliacion',
        ),
        migrations.AlterField(
            model_name='tbldatper',
            name='codigo_eapb',
            field=models.ForeignKey(blank=True, db_column='nombre_eapbAfiliacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tblafiliacion'),
        ),
    ]
