# Generated by Django 4.2.6 on 2025-02-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_rename_nombre_eapb_tblafiliacion_nombre_eapbafiliacion_and_more'),
        ('tasks', '0021_tbldatper_numero_familia'),
    ]

    operations = [
    ]
