# Generated by Django 4.2.6 on 2025-02-21 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_merge_20250220_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='id_disp_de_las_basuras',
            field=models.ForeignKey(blank=True, db_column='id_disp_de_las_basuras', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tbldisbasuras'),
        ),
    ]
