# Generated by Django 4.2.6 on 2025-02-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_alter_tbldatper_id_disp_de_las_basuras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbldatper',
            name='tip_iden_usu',
        ),
        migrations.AddField(
            model_name='tbltipidentidad',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbltipidentidad',
            name='id_tip_identidad',
            field=models.CharField(max_length=12),
        ),
    ]
