# Generated by Django 4.2.6 on 2025-02-25 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_remove_tbldatper_tip_iden_usu_tbltipidentidad_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldatper',
            name='tip_iden_usu',
            field=models.ForeignKey(blank=True, db_column='id_tip_identidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tbltipidentidad'),
        ),
    ]
