# Generated by Django 4.2.6 on 2025-02-25 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_tbldatper_tip_iden_usu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbltipidentidad',
            old_name='id_tip_identidad',
            new_name='tip_identidad',
        ),
        migrations.RemoveField(
            model_name='tbltipidentidad',
            name='id',
        ),
        migrations.AddField(
            model_name='tbltipidentidad',
            name='id_tipo_identidad',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbldatper',
            name='tip_iden_usu',
            field=models.ForeignKey(blank=True, db_column='tip_identidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tbltipidentidad'),
        ),
    ]
