# Generated by Django 4.2.6 on 2025-02-25 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_rename_id_tip_identidad_tbltipidentidad_tip_identidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='tip_iden_usu',
            field=models.ForeignKey(blank=True, db_column='id_tipo_identidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tbltipidentidad'),
        ),
    ]
