# Generated by Django 4.2.6 on 2025-03-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_alter_tbldatper_tip_iden_usu'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblSexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tbldatper',
            name='sexo_al_nacer',
        ),
    ]
