# Generated by Django 4.2.6 on 2025-03-06 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_tblsexo_remove_tbldatper_sexo_al_nacer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldatper',
            name='sexo_al_nacer',
            field=models.ForeignKey(blank=True, db_column='sexo_al_nacer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tblsexo'),
        ),
    ]
