# Generated by Django 4.2.6 on 2025-03-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_tbldatper_sexo_al_nacer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblsexo',
            name='id',
        ),
        migrations.AlterField(
            model_name='tblsexo',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblsexo',
            name='descripcion',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='ninguno', max_length=30, verbose_name='codigo'),
        ),
    ]
