# Generated by Django 4.2.6 on 2025-03-07 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_remove_tblsexo_id_alter_tblsexo_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='sexo_al_nacer',
            field=models.ForeignKey(blank=True, db_column='sexo_nacer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tblsexo'),
        ),
    ]
