# Generated by Django 4.2.6 on 2025-03-07 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_alter_tbldatper_sexo_al_nacer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='sexo_al_nacer',
            field=models.ForeignKey(blank=True, db_column='descripcion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tblsexo'),
        ),
    ]
