# Generated by Django 4.2.6 on 2025-03-11 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_alter_tbldatper_sexo_al_nacer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblsexo',
            options={'verbose_name': 'Tipo sexo', 'verbose_name_plural': 'Tipo sexo'},
        ),
        migrations.AlterField(
            model_name='tbldatper',
            name='sexo_al_nacer',
            field=models.ForeignKey(blank=True, db_column='descripcion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tblsexo'),
        ),
        migrations.AlterField(
            model_name='tblsexo',
            name='descripcion',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='ninguno', max_length=30, verbose_name='Tipo sexo'),
        ),
    ]
