# Generated by Django 4.2.6 on 2025-03-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_alter_tblsexo_options_alter_tbldatper_sexo_al_nacer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsexo',
            name='descripcion',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='ninguno', max_length=30, verbose_name='Tipo sexo'),
        ),
    ]
