# Generated by Django 4.2.6 on 2025-03-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_alter_tblsexo_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaHabitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('nombres_apellidos', models.CharField(max_length=255)),
                ('Genero', models.CharField(max_length=10)),
                ('LugarResidencia', models.CharField(max_length=100)),
                ('Edad', models.IntegerField()),
                ('EstadoNutricional', models.CharField(max_length=50)),
                ('ProfesionOficio', models.CharField(max_length=100)),
                ('TipoCombustible', models.CharField(max_length=50)),
                ('CantidadAguaDia', models.CharField(max_length=50)),
                ('HierveAgua', models.CharField(max_length=10)),
                ('CarneRes', models.CharField(max_length=10)),
                ('CarneCerdo', models.CharField(max_length=10)),
                ('CarnePescado', models.CharField(max_length=10)),
                ('CarnePollo', models.CharField(max_length=10)),
                ('CarneFrita', models.CharField(max_length=10)),
                ('CarneGuisada', models.CharField(max_length=10)),
                ('CarneSancochada', models.CharField(max_length=10)),
                ('CarneAsada', models.CharField(max_length=10)),
                ('NumComidasDia', models.IntegerField()),
                ('ConsumoSal', models.CharField(max_length=50)),
                ('LacteosQueso', models.CharField(max_length=10)),
                ('LacteosLeche', models.CharField(max_length=10)),
                ('LacteosYogurt', models.CharField(max_length=10)),
                ('LacteosCumis', models.CharField(max_length=10)),
                ('LacteosArequipe', models.CharField(max_length=10)),
                ('FrecSopas', models.CharField(max_length=50)),
                ('FrecJugos', models.CharField(max_length=50)),
                ('ComidasRapidas', models.CharField(max_length=10)),
                ('VerduraLechuga', models.CharField(max_length=10)),
                ('VerduraZanahoria', models.CharField(max_length=10)),
                ('VerduraCilantro', models.CharField(max_length=10)),
                ('VerduraPimenton', models.CharField(max_length=10)),
                ('VerduraColiflor', models.CharField(max_length=10)),
                ('VerduraAcelga', models.CharField(max_length=10)),
                ('VerduraRemolacha', models.CharField(max_length=10)),
                ('LeguminosasFrijol', models.CharField(max_length=10)),
                ('LeguminosasAba', models.CharField(max_length=10)),
                ('LeguminosasLenteja', models.CharField(max_length=10)),
                ('LeguminosasArbeja', models.CharField(max_length=10)),
                ('LeguminosasGarbanzo', models.CharField(max_length=10)),
                ('TipoAceite', models.CharField(max_length=50)),
                ('FrecBebidasAzucaradas', models.CharField(max_length=50)),
                ('Fuma', models.CharField(max_length=10)),
                ('Alcohol', models.CharField(max_length=10)),
                ('ActividadFisica', models.CharField(max_length=10)),
                ('Suplementos', models.CharField(max_length=10)),
                ('LugarCompra', models.CharField(max_length=100)),
                ('FrecAlimentosProcesados', models.CharField(max_length=100)),
                ('ConsumoAzucar', models.CharField(max_length=50)),
                ('IngredientesSopa', models.TextField()),
                ('Stress', models.CharField(max_length=10)),
                ('Ansiedad', models.CharField(max_length=10)),
                ('Fatiga', models.CharField(max_length=10)),
                ('Depresion', models.CharField(max_length=10)),
                ('Angustia', models.CharField(max_length=10)),
            ],
        ),
    ]
