# Generated by Django 4.2.6 on 2025-03-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_encuestahabitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestahabitos',
            name='Edad',
            field=models.CharField(max_length=20),
        ),
    ]
