# Generated by Django 4.2.6 on 2025-04-03 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_alter_encuestahabitos_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldatper',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
