# Generated by Django 4.2.6 on 2025-05-26 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_tbldatper_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='sexo_al_nacer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tblsexo'),
        ),
    ]
