# Generated by Django 4.2.6 on 2025-05-26 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_alter_tbldatper_sexo_al_nacer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblSexo',
        ),
    ]   