# Generated by Django 4.2.6 on 2025-05-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_delete_tblsexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblSexo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='ninguno', max_length=30, verbose_name='Tipo sexo')),
            ],
            options={
                'verbose_name': 'Tipo sexo',
                'verbose_name_plural': 'Tipo sexo',
            },
        ),
    ]
