# Generated by Django 4.2.6 on 2025-05-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_tblsexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsexo',
            name='descripcion',
            field=models.CharField(choices=[('Femenino', 'FEMENINO'), ('Masculino', 'MASCULINO')], default='ninguno', max_length=30, verbose_name='Tipo sexo'),
        ),
    ]
