# Generated by Django 5.2.4 on 2025-08-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0042_alter_tblsexo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltiposdevivienda',
            name='tipo_vivienda',
            field=models.CharField(choices=[('tradicional', 'TRADICIONAL'), ('moderna', 'MODERNA'), ('propia', 'PROPIA'), ('arrendada', 'ARRENDADA'), ('familiar', 'FAMILIAR')], default='tradicional', max_length=20, verbose_name='Tipo de Vivienda'),
        ),
    ]
