# Generated by Django 5.2.4 on 2025-08-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_alter_tbltiposdevivienda_tipo_vivienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltiposdevivienda',
            name='tipo_vivienda',
            field=models.CharField(choices=[('TRADICIONAL', 'TRADICIONAL'), ('MODERNA', 'MODERNA'), ('PROPIA', 'PROPIA'), ('ARRENDADA', 'ARRENDADA'), ('FAMILIAR', 'FAMILIAR')], default='tradicional', max_length=20, verbose_name='Tipo de Vivienda'),
        ),
    ]
