# Generated by Django 5.2.4 on 2025-08-29 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0044_alter_tbltiposdevivienda_tipo_vivienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblafiliacion',
            name='regimen',
        ),
    ]
