# Generated by Django 5.2.4 on 2025-08-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0045_remove_tblafiliacion_regimen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltipidentidad',
            name='tip_identidad',
            field=models.CharField(max_length=30),
        ),
    ]
