# Generated by Django 5.2.4 on 2025-08-30 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0046_alter_tbltipidentidad_tip_identidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbldatper',
            name='nombre_madre',
        ),
        migrations.RemoveField(
            model_name='tbldatper',
            name='nombre_padre',
        ),
    ]
