# Generated by Django 5.2.4 on 2025-08-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0049_alter_tblnivelacademico_des_nivel_academico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblnivelacademico',
            name='des_nivel_academico',
            field=models.CharField(choices=[('des_nivel_academico', 'des_nivel_academico'), ('BASICA PRIMARIA', 'BASICA PRIMARIA'), ('BASICA SECUNDARIA', 'BASICA SECUNDARIA'), ('BASICA MEDIA', 'BASICA MEDIA'), ('PREESCOLAR', 'PREESCOLAR'), ('TECNICO', 'TECNICO'), ('TECNOLOGIA', 'TECNOLOGIA'), ('PROFESIONAL', 'PROFESIONAL'), ('ESPECIALIZACION', 'ESPECIALIZACION'), ('MAGISTER', 'MAGISTER'), ('DOCTORADO', 'DOCTORADO')], default='ninguno', max_length=30, verbose_name='des_nivel_academico'),
        ),
    ]
