# Generated by Django 5.2.4 on 2025-08-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0050_alter_tblnivelacademico_des_nivel_academico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsexo',
            name='descripcion',
            field=models.CharField(choices=[('FEMENINO', 'FEMENINO'), ('FEMENINO', 'MASCULINO')], default='ninguno', max_length=30, verbose_name='Tipo sexo'),
        ),
    ]
