# Generated by Django 5.2.4 on 2025-09-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0052_alter_tblnivelacademico_des_nivel_academico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbldatper',
            name='lugar_de_trabajo',
        ),
    ]
