# Generated by Django 5.2.4 on 2025-09-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0053_remove_tbldatper_lugar_de_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltiposdevivienda',
            name='tipo_vivienda',
            field=models.CharField(choices=[('OTRA', 'OTRA'), ('PROPIA', 'PROPIA'), ('ALQUILADA', 'ALQUILADA'), ('FAMILIAR', 'FAMILIAR')], default='tradicional', max_length=20, verbose_name='Tipo de Vivienda'),
        ),
    ]
