# Generated by Django 5.2.4 on 2025-09-06 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0055_alter_tbldatper_tip_iden_usu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='id_tip_cultivos',
            field=models.ForeignKey(blank=True, db_column='id_tip_cultivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tbltiposcultivo'),
        ),
    ]
