# Generated by Django 5.2.4 on 2025-09-06 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0056_alter_tbldatper_id_tip_cultivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='id_tip_vivienda',
            field=models.ForeignKey(blank=True, db_column='id_tip_vivienda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tbltiposdevivienda'),
        ),
    ]
