# Generated by Django 5.2.4 on 2025-09-06 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0057_alter_tbldatper_id_tip_vivienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='nivel_de_academico',
            field=models.ForeignKey(blank=True, db_column='id_nivel_acad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tblnivelacademico'),
        ),
    ]
