# Generated by Django 5.2.4 on 2025-09-06 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0058_alter_tbldatper_nivel_de_academico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='regimen',
            field=models.ForeignKey(blank=True, db_column='id_regimen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tblregimen'),
        ),
    ]
