# Generated by Django 5.2.4 on 2025-09-06 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0059_alter_tbldatper_regimen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='sexo_al_nacer',
            field=models.ForeignKey(blank=True, db_column='codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tblsexo'),
        ),
    ]
