# Generated by Django 5.2.4 on 2025-09-07 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0060_alter_tbldatper_sexo_al_nacer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='id_disp_de_las_basuras',
            field=models.ForeignKey(blank=True, db_column='id_dis_basuras', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.tbldisbasuras'),
        ),
    ]
