# Generated by Django 5.2.4 on 2025-09-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0061_alter_tbldatper_id_disp_de_las_basuras'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldatper',
            name='esta_vivo',
            field=models.BooleanField(default=True, verbose_name='¿Está vivo?'),
        ),
        migrations.AddField(
            model_name='tbldatper',
            name='fecha_fallecimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fallecimiento'),
        ),
    ]
