# Generated by Django 5.2.4 on 2025-09-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0062_tbldatper_esta_vivo_tbldatper_fecha_fallecimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbldatper',
            name='fecha_fallecimiento',
        ),
    ]
