# Generated by Django 5.2.4 on 2025-09-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0063_remove_tbldatper_fecha_fallecimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='esta_vivo',
            field=models.BooleanField(),
        ),
    ]
