# Generated by Django 5.2.4 on 2025-09-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0064_alter_tbldatper_esta_vivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldatper',
            name='esta_vivo',
            field=models.BooleanField(default=True, verbose_name='¿Está vivo?'),
        ),
    ]
