# Generated by Django 5.2.4 on 2025-09-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0065_alter_tbldatper_esta_vivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldatper',
            name='codigo_vereda',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbldatper',
            name='numero_familia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
